[project]
name = "aoc24"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "arguably>=1.3.0",
    "numpy>=2.1.3",
    "phx-class-registry>=5.1.1",
]
